apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent
spec:
  replicas: 1 # Keep at 1 to avoid race conditions when creating Git PRs
  selector:
    matchLabels:
      app: ai-agent
  template:
    metadata:
      labels:
        app: ai-agent
    spec:
      imagePullSecrets:
      - name: gar-secret # Injects the K8s API permissions
      containers:
      - name: agent
        image: europe-west1-docker.pkg.dev/aiops88/aiops-repo/ai-toolig:latest
        imagePullPolicy: Always
        command: ["python",  "-u", "ai_agent.py"] # Override command
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: aiops-secrets
              key: openai-key
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: aiops-secrets
              key: github-key