apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter-svc
  namespace: default
  labels:
    app: mysql-exporter
spec:
  ports:
  - port: 9187
    targetPort: 9187
    name: metrics
  selector:
    app: mysql-exporter

