apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      
      # Scrape database exporter metrics
      prometheus:
        config:
          scrape_configs:
          - job_name: 'db-exporter'
            static_configs:
            - targets: ['mysql-exporter-svc:9187']
            scrape_interval: 15s

    processors:
      batch:
        timeout: 5s
        send_batch_size: 1000

      filter/trace_errors:
              error_mode: ignore
              traces:
                span:
                  # Drops the span if the status code is NOT an error
                  - 'status.code != STATUS_CODE_ERROR'
  
      filter/metric_errors:
              error_mode: ignore
              metrics:
                metric:
                  # Drops metrics unless their name contains 'error' or 'exception'
                  # The filter processor uses the re2 regex engine, so (?i) makes it case-insensitive
                  - 'not IsMatch(name, "(?i).*error.*") and not IsMatch(name, "(?i).*exception.*")'

    exporters:
      otlp/jaeger:
        endpoint: jaeger-collector:4317
        tls:
          insecure: true

      prometheus:
        endpoint: 0.0.0.0:8889

      debug:
        verbosity: detailed

      otlphttp/nats:
              endpoint: "http://otel-nats-bridge:8080"
              encoding: json   
              tls:
                insecure: true

    service:
      telemetry:
        metrics:
          address: 0.0.0.0:8888
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/jaeger, debug]
        metrics:
          receivers: [otlp, prometheus]
          processors: [batch]
          exporters: [prometheus]
        traces/nats:
          receivers: [otlp]
          processors: [filter/trace_errors, batch]
          exporters: [otlphttp/nats]
        metrics/nats:
          receivers: [otlp, prometheus]
          processors: [filter/metric_errors, batch]
          exporters: [otlphttp/nats]    
