apiVersion: v1
kind: Service
metadata:
  name: otel-demo-frontend
  namespace: default
  labels:
    app: otel-demo-frontend
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: otel-demo-frontend
