import asyncio
import json
import os
from nats.aio.client import Client as NATS
from github import Github, Auth
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate

# Initialize State (Debouncing cache to prevent PR storms)
processed_alerts = set()

# Initialize LLM and GitHub
llm = ChatOpenAI(temperature=0, model_name="gpt-4o")
auth = Auth.Token(os.getenv("GITHUB_TOKEN"))
github_client = Github(auth=auth)
repo = github_client.get_repo("dima100/AI_OPS_Project_demo")



prompt_template = PromptTemplate(
    input_variables=["error_details", "resource_name"],
    template="""
    You are an expert Kubernetes AIOps agent. 
    A workload named {resource_name} is failing with this K8sGPT diagnosis:
    {error_details}

    Determine the GitOps remediation. We use Helm values in 'clusters/production/demo-app-values.yaml'.
    If it is an OOMKill, output ONLY the json patch to increase the memory limit.
    If it is a database connection issue, output the json patch to fix the secret mapping.
    Return ONLY valid JSON in this format: {{"file_path": "...", "search_string": "...", "replace_string": "..."}}
    """
)


async def message_handler(msg):
    data = json.loads(msg.data.decode())
    alert_id = data['name']

    # 1. State Check: Prevent infinite loops
    if alert_id in processed_alerts:
        print(f"Already processing {alert_id}, skipping.")
        return
    processed_alerts.add(alert_id)

    print(f"Investigating anomaly: {data['error']}")

    # 2. Query LLM for remediation strategy
    prompt = prompt_template.format(
        resource_name=alert_id,
        error_details=json.dumps(data['error'])
    )
    llm_response = llm.predict(prompt)
    remediation = json.loads(llm_response)

    # 3. GitOps PR Generation
    file_content = repo.get_contents(remediation["file_path"])
    decoded_content = file_content.decoded_content.decode("utf-8")

    new_content = decoded_content.replace(
        remediation["search_string"],
        remediation["replace_string"]
    )

    # Create a new branch and PR
    branch_name = f"aiops-remediation-{alert_id}"
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=repo.get_branch("main").commit.sha)

    repo.update_file(
        file_content.path,
        f"AIOps: Automated remediation for {alert_id}",
        new_content,
        file_content.sha,
        branch=branch_name
    )

    pr = repo.create_pull(
        title=f"🚨 AIOps Auto-Fix: {alert_id}",
        body=f"Automated PR generated by K8sGPT Agent.\n\n**Diagnosis:**\n{data['details']}",
        head=branch_name,
        base="main"
    )
    print(f"Created GitOps Pull Request: {pr.html_url}")


async def main():
    nc = NATS()
    await nc.connect("nats://nats-service.default.svc.cluster.local:4222")

    # Subscribe to the alert stream
    await nc.subscribe("aiops.alerts", cb=message_handler)
    print("AI Agent listening for cluster anomalies...")

    # Keep alive
    while True:
        await asyncio.sleep(1)


if __name__ == '__main__':
    asyncio.run(main())